all:
  hosts:
    node1:
      ansible_host: 142.132.174.12
      ip: 142.132.174.12
      access_ip: 142.132.174.12
    node2:
      ansible_host: 65.108.151.3
      ip: 65.108.151.3
      access_ip: 65.108.151.3
    node3:
      ansible_host: 65.108.152.166
      ip: 65.108.152.166
      access_ip: 65.108.152.166
  children:
    kube_control_plane:
      hosts:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
