apiVersion: batch/v1
kind: Job
metadata:
  name: exercise
spec:
  template:
    spec:
      containers:
      - name: exercise
        image: jany15/dnation-entry-exercise
        command: ["python", "exercise.py"]
        volumeMounts:
        - name: matrix-volume
          mountPath: /app/matrix.txt
          subPath: matrix.txt
      restartPolicy: Never
      volumes:
      - name: matrix-volume
        configMap:
          name: exercise
          items:
          - key: matrix.txt
            path: matrix.txt
  backoffLimit: 4